package rP_General

import (
	"github.com/remrafvil/Auriga_API/internal/repositories/rProducts/rP_Types"
)

var MotorsToCreate = []rP_Types.ProductCreationData{
	{
		Name:         "3GEB103722-HDA",
		ProductType:  "Motor_AC",
		Manufacturer: "ABB",
		Family:       "M3EB",
		Description:  "Motor HDP",
		FeatureValues: map[string]string{
			"Nominal Power":    "4.0",
			"Stator Voltage":   "400.0",
			"Stator Current":   "10.3",
			"Nominal Speed":    "1500.0",
			"Frequency":        "77.3",
			"Power Factor":     "0.636",
			"Efficiency":       "87.9",
			"Torque":           "25.5",
			"Maximum Speed":    "3000.0",
			"Water Flow":       "0",
			"Frame":            "M3EB 100B 6",
			"Cooling":          "AirCooling: Forze",
			"TempSensor":       "KLX",
			"MountingPosition": "IMB35 - IM2001",
			"InsulationClass":  "H",
			"EfficiencyClass":  "IE3",
			"Bearing_DE":       "NU308/LGMT3",
			"Bearing_NDE":      "6206-2Z/C3",
		},
	},
	{
		Name:         "3GEB103742-HDA",
		ProductType:  "Motor_AC",
		Manufacturer: "ABB",
		Family:       "M3EB",
		Description:  "Motor HDP",
		FeatureValues: map[string]string{
			"Nominal Power":    "7.4",
			"Stator Voltage":   "400.0",
			"Stator Current":   "18.4",
			"Nominal Speed":    "1500.0",
			"Frequency":        "77.2",
			"Power Factor":     "0.650",
			"Efficiency":       "89.4",
			"Torque":           "47.1",
			"Maximum Speed":    "3000.0",
			"Water Flow":       "0",
			"Frame":            "M3EB 100D 6",
			"Cooling":          "AirCooling: Forze",
			"TempSensor":       "Pt100",
			"MountingPosition": "IMB35 - IM2001",
			"InsulationClass":  "H",
			"EfficiencyClass":  "IE3",
			"Bearing_DE":       "NU308/LGMT3",
			"Bearing_NDE":      "6206-2Z/C3",
		},
	},
	{
		Name:         "3GEB132722-HDA",
		ProductType:  "Motor_AC",
		Manufacturer: "ABB",
		Family:       "M3EB",
		Description:  "Motor HDP",
		FeatureValues: map[string]string{
			"Nominal Power":    "14.8",
			"Stator Voltage":   "400.0",
			"Stator Current":   "32.1",
			"Nominal Speed":    "1500.0",
			"Frequency":        "51.5",
			"Power Factor":     "0.751",
			"Efficiency":       "88.5",
			"Torque":           "94.7",
			"Maximum Speed":    "3750.0",
			"Water Flow":       "0",
			"Frame":            "M3EB 132B 4",
			"Cooling":          "AirCooling: Forze",
			"TempSensor":       "Pt100",
			"MountingPosition": "IMB35 - IM2001",
			"InsulationClass":  "H",
			"EfficiencyClass":  "IE3",
			"Bearing_DE":       "NU310/LGMT3",
			"Bearing_NDE":      "6308-2Z/C3",
		},
	},
	{
		Name:         "3GEB132742-HDA",
		ProductType:  "Motor_AC",
		Manufacturer: "ABB",
		Family:       "M3EB",
		Description:  "Motor HDP",
		FeatureValues: map[string]string{
			"Nominal Power":    "23.0",
			"Stator Voltage":   "400.0",
			"Stator Current":   "46.3",
			"Nominal Speed":    "1500.0",
			"Frequency":        "51.5",
			"Power Factor":     "0.812",
			"Efficiency":       "90.2",
			"Torque":           "149.6",
			"Maximum Speed":    "3750.0",
			"Water Flow":       "0",
			"Frame":            "M3EB 132D 4",
			"Cooling":          "AirCooling: Forze",
			"TempSensor":       "Pt100",
			"MountingPosition": "IMB35 - IM2001",
			"InsulationClass":  "H",
			"EfficiencyClass":  "IE3",
			"Bearing_DE":       "NU310/LGMT3",
			"Bearing_NDE":      "6308-2Z/C3",
		},
	},
	{
		Name:         "3GEB162722-HDA",
		ProductType:  "Motor_AC",
		Manufacturer: "ABB",
		Family:       "M3EB",
		Description:  "Motor HDP",
		FeatureValues: map[string]string{
			"Nominal Power":    "37.0",
			"Stator Voltage":   "400.0",
			"Stator Current":   "70.7",
			"Nominal Speed":    "1500.0",
			"Frequency":        "50.8",
			"Power Factor":     "0.815",
			"Efficiency":       "90.6",
			"Torque":           "236.0",
			"Maximum Speed":    "3750.0",
			"Water Flow":       "0",
			"Frame":            "M3EB 160B 4",
			"Cooling":          "AirCooling: Forze",
			"TempSensor":       "Pt100",
			"MountingPosition": "IMB35 - IM2001",
			"InsulationClass":  "H",
			"EfficiencyClass":  "IE3",
			"Bearing_DE":       "NU312/LGMT3",
			"Bearing_NDE":      "6309-2Z/C3",
		},
	},
	{
		Name:         "3GEB162752-HDA",
		ProductType:  "Motor_AC",
		Manufacturer: "ABB",
		Family:       "M3EB",
		Description:  "Motor HDP",
		FeatureValues: map[string]string{
			"Nominal Power":    "59.0",
			"Stator Voltage":   "400.0",
			"Stator Current":   "107.7",
			"Nominal Speed":    "1500.0",
			"Frequency":        "50.8",
			"Power Factor":     "0.845",
			"Efficiency":       "93.4",
			"Torque":           "375.0",
			"Maximum Speed":    "3750.0",
			"Water Flow":       "0",
			"Frame":            "M3EB 160E 4",
			"Cooling":          "AirCooling: Forze",
			"TempSensor":       "Pt100",
			"MountingPosition": "IMB35 - IM2001",
			"InsulationClass":  "H",
			"EfficiencyClass":  "IE3",
			"Bearing_DE":       "NU312/LGMT3",
			"Bearing_NDE":      "6309-2Z/C3",
		},
	},
	{
		Name:         "3GEB202732-HDA",
		ProductType:  "Motor_AC",
		Manufacturer: "ABB",
		Family:       "M3EB",
		Description:  "Motor HDP",
		FeatureValues: map[string]string{
			"Nominal Power":    "72.3",
			"Stator Voltage":   "400.0",
			"Stator Current":   "140.0",
			"Nominal Speed":    "1500.0",
			"Frequency":        "50.5",
			"Power Factor":     "0.790",
			"Efficiency":       "94.3",
			"Torque":           "462.0",
			"Maximum Speed":    "3750.0",
			"Water Flow":       "0",
			"Frame":            "M3EB 200C 4",
			"Cooling":          "AirCooling: Forze",
			"TempSensor":       "Pt100",
			"MountingPosition": "IMB35 - IM2001",
			"InsulationClass":  "H",
			"EfficiencyClass":  "IE3",
			"Bearing_DE":       "NU315/LGMT3",
			"Bearing_NDE":      "6314-2Z/C3",
		},
	},
	{
		Name:         "3GEB202752-HDA",
		ProductType:  "Motor_AC",
		Manufacturer: "ABB",
		Family:       "M3EB",
		Description:  "Motor HDP",
		FeatureValues: map[string]string{
			"Nominal Power":    "94.5",
			"Stator Voltage":   "400.0",
			"Stator Current":   "170.0",
			"Nominal Speed":    "1500.0",
			"Frequency":        "50.4",
			"Power Factor":     "0.847",
			"Efficiency":       "95.0",
			"Torque":           "602.0",
			"Maximum Speed":    "3750.0",
			"Water Flow":       "0",
			"Frame":            "M3EB 200E 4",
			"Cooling":          "AirCooling: Forze",
			"TempSensor":       "Pt100",
			"MountingPosition": "IMB35 - IM2001",
			"InsulationClass":  "H",
			"EfficiencyClass":  "IE3",
			"Bearing_DE":       "NU315/LGMT3",
			"Bearing_NDE":      "6314-2Z/C3",
		},
	},
	{
		Name:         "3GEB252722-_DA",
		ProductType:  "Motor_AC",
		Manufacturer: "ABB",
		Family:       "M3EB",
		Description:  "Motor HDP",
		FeatureValues: map[string]string{
			"Nominal Power":    "150.0",
			"Stator Voltage":   "400.0",
			"Stator Current":   "262.0",
			"Nominal Speed":    "1500.0",
			"Frequency":        "50.4",
			"Power Factor":     "0.864",
			"Efficiency":       "95.5",
			"Torque":           "955.0",
			"Maximum Speed":    "3600.0",
			"Water Flow":       "0",
			"Frame":            "M3EB 250A 4",
			"Cooling":          "AirCooling: Forze",
			"TempSensor":       "Pt100",
			"MountingPosition": "IMB35 - IM2001",
			"InsulationClass":  "H",
			"EfficiencyClass":  "IE3",
			"Bearing_DE":       "NU322EC/C3",
			"Bearing_NDE":      "6319MC4VL0241",
		},
	},
	{
		Name:         "3GEB252742-_DA",
		ProductType:  "Motor_AC",
		Manufacturer: "ABB",
		Family:       "M3EB",
		Description:  "Motor HDP",
		FeatureValues: map[string]string{
			"Nominal Power":    "218.0",
			"Stator Voltage":   "400.0",
			"Stator Current":   "385.0",
			"Nominal Speed":    "1500.0",
			"Frequency":        "50.3",
			"Power Factor":     "0.852",
			"Efficiency":       "95.9",
			"Torque":           "1389.0",
			"Maximum Speed":    "3600.0",
			"Water Flow":       "0",
			"Frame":            "M3EB 250D 4",
			"Cooling":          "AirCooling: Forze",
			"TempSensor":       "Pt100",
			"MountingPosition": "IMB3 - IM1001",
			"InsulationClass":  "H",
			"EfficiencyClass":  "IE3",
			"Bearing_DE":       "NU322EC/C3",
			"Bearing_NDE":      "6319MC4VL0241",
		},
	},
}
