package rP_General

import (
	"github.com/remrafvil/Auriga_API/internal/repositories/rProducts/rP_Types"
)

var DrivesToCreate = []rP_Types.ProductCreationData{
	{
		Name:         "ACS880-104-006A0-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "6.0",
			"Maximum Current":    "8.80",
			"Nominal Power":      "3.0",
			"Heavy Duty Current": "5.0",
			"Heavy Duty Power":   "2.20",
			"Dissipated Power":   "0.080",
			"Frame":              "R1i",
		},
	},
	{
		Name:         "ACS880-104-0014A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "14.0",
			"Maximum Current":    "16.5",
			"Nominal Power":      "7.5",
			"Heavy Duty Current": "11.0",
			"Heavy Duty Power":   "5.5",
			"Dissipated Power":   "0.150",
			"Frame":              "R2i",
		},
	},
	{
		Name:         "ACS880-104-0035A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "35.0",
			"Maximum Current":    "44.0",
			"Nominal Power":      "22.0",
			"Heavy Duty Current": "29.0",
			"Heavy Duty Power":   "18.80",
			"Dissipated Power":   "0.220",
			"Frame":              "R3i",
		},
	},
	{
		Name:         "ACS880-104-0078A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "78.0",
			"Maximum Current":    "100.0",
			"Nominal Power":      "45.0",
			"Heavy Duty Current": "69.0",
			"Heavy Duty Power":   "45.0",
			"Dissipated Power":   "0.650",
			"Frame":              "R4i",
		},
	},
	{
		Name:         "ACS880-104-0140A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "140.0",
			"Maximum Current":    "136.0",
			"Nominal Power":      "90.0",
			"Heavy Duty Current": "102.0",
			"Heavy Duty Power":   "55.0",
			"Dissipated Power":   "1.20",
			"Frame":              "R6i",
		},
	},
	{
		Name:         "ACS880-104-0200A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "200.0",
			"Maximum Current":    "197.0",
			"Nominal Power":      "132.0",
			"Heavy Duty Current": "147.0",
			"Heavy Duty Power":   "90.0",
			"Dissipated Power":   "1.80",
			"Frame":              "R6i",
		},
	},
	{
		Name:         "ACS880-104-0340A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "340.0",
			"Maximum Current":    "340.0",
			"Nominal Power":      "250.0",
			"Heavy Duty Current": "254.0",
			"Heavy Duty Power":   "160.0",
			"Dissipated Power":   "3.20",
			"Frame":              "R7i",
		},
	},
	{
		Name:         "ACS880-104-0440A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "440.0",
			"Maximum Current":    "440.0",
			"Nominal Power":      "250.0",
			"Heavy Duty Current": "329.0",
			"Heavy Duty Power":   "200.0",
			"Dissipated Power":   "4.70",
			"Frame":              "R8i",
		},
	},
	{
		Name:         "ACS880-104-0740A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "740.0",
			"Maximum Current":    "740.0",
			"Nominal Power":      "500.0",
			"Heavy Duty Current": "554.0",
			"Heavy Duty Power":   "355.0",
			"Dissipated Power":   "8.10",
			"Frame":              "R8i",
		},
	},
	{
		Name:         "ACS880-304-0980A-5",
		ProductType:  "Rectifier_ISU",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier",
		FeatureValues: map[string]string{
			"Nominal Current":    "980.0",
			"Maximum Current":    "1680.0",
			"Nominal Power":      "849.0",
			"Heavy Duty Current": "648.0",
			"Heavy Duty Power":   "0.0",
			"Dissipated Power":   "6.00",
			"Frame":              "D8D",
		},
	},
	{
		Name:         "ACS880-204-0015A-5",
		ProductType:  "Rectifier_ISU",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier",
		FeatureValues: map[string]string{
			"Nominal Current":    "18.0",
			"Maximum Current":    "24.0",
			"Nominal Power":      "13.0",
			"Heavy Duty Current": "14.0",
			"Heavy Duty Power":   "10.0",
			"Dissipated Power":   "0.17",
			"Frame":              "R2i",
		},
	},
	{
		Name:         "WFU-02",
		ProductType:  "LCL_Filter",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier Filter",
		FeatureValues: map[string]string{
			"Nominal Current":  "15.0",
			"Dissipated Power": "0.33",
		},
	},
	{
		Name:         "ACS880-204-0029A-5",
		ProductType:  "Rectifier_ISU",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier",
		FeatureValues: map[string]string{
			"Nominal Current":    "35.0",
			"Maximum Current":    "46.0",
			"Nominal Power":      "25.0",
			"Heavy Duty Current": "26.0",
			"Heavy Duty Power":   "19.0",
			"Dissipated Power":   "0.32",
			"Frame":              "R3i",
		},
	},
	{
		Name:         "WFU-11",
		ProductType:  "LCL_Filter",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier Filter",
		FeatureValues: map[string]string{
			"Nominal Current":  "29.0",
			"Dissipated Power": "0.65",
		},
	},
	{
		Name:         "ACS880-204-0077A-5",
		ProductType:  "Rectifier_ISU",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier",
		FeatureValues: map[string]string{
			"Nominal Current":    "93.0",
			"Maximum Current":    "121.0",
			"Nominal Power":      "66.0",
			"Heavy Duty Current": "70.0",
			"Heavy Duty Power":   "49.0",
			"Dissipated Power":   "0.8",
			"Frame":              "R4i",
		},
	},
	{
		Name:         "WFU-22",
		ProductType:  "LCL_Filter",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier Filter",
		FeatureValues: map[string]string{
			"Nominal Current":  "77.0",
			"Dissipated Power": "1.78",
		},
	},
	{
		Name:         "ACS880-01-021A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "21.0",
			"Maximum Current":    "29.0",
			"Nominal Power":      "7.5",
			"Heavy Duty Current": "14.0",
			"Heavy Duty Power":   "5.5",
			"Dissipated Power":   "0.330",
			"Frame":              "R2",
		},
	},
	{
		Name:         "ACS880-01-034A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "34.0",
			"Maximum Current":    "54.0",
			"Nominal Power":      "15.0",
			"Heavy Duty Current": "14.0",
			"Heavy Duty Power":   "5.5",
			"Dissipated Power":   "0.4530",
			"Frame":              "R3",
		},
	},
	{
		Name:         "ACS880-01-052A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "52.0",
			"Maximum Current":    "76.0",
			"Nominal Power":      "22.0",
			"Heavy Duty Current": "14.0",
			"Heavy Duty Power":   "5.5",
			"Dissipated Power":   "0.600",
			"Frame":              "R4",
		},
	},
	{
		Name:         "ACS880-01-077A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "77.0",
			"Maximum Current":    "122.0",
			"Nominal Power":      "37.0",
			"Heavy Duty Current": "14.0",
			"Heavy Duty Power":   "5.5",
			"Dissipated Power":   "0.9160",
			"Frame":              "R5",
		},
	},
	{
		Name:         "ACS880-01-156A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "156.0",
			"Maximum Current":    "247.0",
			"Nominal Power":      "75.0",
			"Heavy Duty Current": "14.0",
			"Heavy Duty Power":   "5.5",
			"Dissipated Power":   "1.840",
			"Frame":              "R7",
		},
	},
	{
		Name:         "ACS880-01-180A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "180.0",
			"Maximum Current":    "287.0",
			"Nominal Power":      "90.0",
			"Heavy Duty Current": "14.0",
			"Heavy Duty Power":   "5.5",
			"Dissipated Power":   "2.2810",
			"Frame":              "R7",
		},
	},
	{
		Name:         "ACS880-01-240A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "240.0",
			"Maximum Current":    "350.0",
			"Nominal Power":      "110.0",
			"Heavy Duty Current": "14.0",
			"Heavy Duty Power":   "5.5",
			"Dissipated Power":   "2.9120",
			"Frame":              "R8",
		},
	},
	{
		Name:         "ACS880-01-361A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "361.0",
			"Maximum Current":    "542.0",
			"Nominal Power":      "200.0",
			"Heavy Duty Current": "14.0",
			"Heavy Duty Power":   "5.5",
			"Dissipated Power":   "4.7810",
			"Frame":              "R9",
		},
	},
	{
		Name:         "ACS880-01-414A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "414.0",
			"Maximum Current":    "542.0",
			"Nominal Power":      "200.0",
			"Heavy Duty Current": "14.0",
			"Heavy Duty Power":   "5.5",
			"Dissipated Power":   "5.6720",
			"Frame":              "R9",
		},
	},
	{
		Name:         "ACS880-01-583A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "583.0",
			"Maximum Current":    "730.0",
			"Nominal Power":      "400.0",
			"Heavy Duty Current": "14.0",
			"Heavy Duty Power":   "5.5",
			"Dissipated Power":   "6.8270",
			"Frame":              "R10",
		},
	},
	{
		Name:         "ACS880-M04-06A0-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "5.5",
			"Maximum Current":    "9.40",
			"Nominal Power":      "7.5",
			"Heavy Duty Current": "14.0",
			"Heavy Duty Power":   "2.20",
			"Dissipated Power":   "0.1480",
			"Frame":              "R1",
		},
	},
	{
		Name:         "ACS880-M04-014A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "12.0",
			"Maximum Current":    "18.0",
			"Nominal Power":      "7.5",
			"Heavy Duty Current": "14.0",
			"Heavy Duty Power":   "5.5",
			"Dissipated Power":   "0.250",
			"Frame":              "R2",
		},
	},
	{
		Name:         "ACS880-M04-018A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "16.0",
			"Maximum Current":    "23.0",
			"Nominal Power":      "7.5",
			"Heavy Duty Current": "14.0",
			"Heavy Duty Power":   "7.5",
			"Dissipated Power":   "0.3180",
			"Frame":              "R2",
		},
	},
	{
		Name:         "ACS880-M04-030A-5",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "26.0",
			"Maximum Current":    "36.0",
			"Nominal Power":      "7.5",
			"Heavy Duty Current": "14.0",
			"Heavy Duty Power":   "11.0",
			"Dissipated Power":   "0.4850",
			"Frame":              "R3",
		},
	},
	{
		Name:         "ACS480-04-02A7-4",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS480",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "2.60",
			"Maximum Current":    "3.2",
			"Nominal Power":      "7.5",
			"Heavy Duty Current": "14.0",
			"Heavy Duty Power":   "0.550",
			"Dissipated Power":   "0.0440",
			"Frame":              "R1",
		},
	},
	{
		Name:         "ACS800-01-0205-3",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS800",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "260.0",
			"Maximum Current":    "326.0",
			"Nominal Power":      "160",
			"Heavy Duty Current": "215.0",
			"Heavy Duty Power":   "132",
			"Dissipated Power":   "3.8",
			"Frame":              "R6",
		},
	},
	{
		Name:         "ACS800-01-0040-3",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS800",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "48.0",
			"Maximum Current":    "72.0",
			"Nominal Power":      "30",
			"Heavy Duty Current": "36.0",
			"Heavy Duty Power":   "22",
			"Dissipated Power":   "0.81",
			"Frame":              "R4",
		},
	},
	{
		Name:         "ACS880-01-072A-3",
		ProductType:  "Drive_AC",
		Manufacturer: "ABB",
		Family:       "ACS880",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "72.0",
			"Maximum Current":    "104.0",
			"Nominal Power":      "37.0",
			"Heavy Duty Current": "61.0",
			"Heavy Duty Power":   "30.0",
			"Dissipated Power":   "1.117",
			"Frame":              "R5",
		},
	},
	{
		Name:         "EVS9324-ES",
		ProductType:  "Drive_AC",
		Manufacturer: "Lenze",
		Family:       "EVS",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "7.0",
			"Maximum Current":    "10.5",
			"Nominal Power":      "4",
			"Heavy Duty Current": "5.20",
			"Heavy Duty Power":   "3",
			"Dissipated Power":   "0.20",
			"Frame":              "B",
		},
	},
	{
		Name:         "EVS9325-ES",
		ProductType:  "Drive_AC",
		Manufacturer: "Lenze",
		Family:       "EVS",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "23.0",
			"Maximum Current":    "19.5",
			"Nominal Power":      "7.5",
			"Heavy Duty Current": "9.7",
			"Heavy Duty Power":   "5.5",
			"Dissipated Power":   "0.26",
			"Frame":              "C",
		},
	},
	{
		Name:         "EVS9326-ES",
		ProductType:  "Drive_AC",
		Manufacturer: "Lenze",
		Family:       "EVS",
		Description:  "AC Rectifier + Inverter",
		FeatureValues: map[string]string{
			"Nominal Current":    "23.5",
			"Maximum Current":    "35.3",
			"Nominal Power":      "15",
			"Heavy Duty Current": "23.0",
			"Heavy Duty Power":   "11",
			"Dissipated Power":   "0.39",
			"Frame":              "D",
		},
	},
}
