package rP_General

import (
	"github.com/remrafvil/Auriga_API/internal/repositories/rProducts/rP_Types"
)

var LinePartsToCreate = []rP_Types.ProductCreationData{
	// ExtrusionLinePatt components
	{
		Name:          "0_Common",
		ProductType:   "LineCommon",
		Manufacturer:  "Coexpan",
		Family:        "ExtrusionLinePatt",
		Description:   "Description",
		FeatureValues: map[string]string{},
	},
	{
		Name:          "1_Transport",
		ProductType:   "LineTransport",
		Manufacturer:  "Coexpan",
		Family:        "ExtrusionLinePatt",
		Description:   "Description",
		FeatureValues: map[string]string{},
	},
	{
		Name:          "2_Dosing",
		ProductType:   "LineDosing",
		Manufacturer:  "Ferlin",
		Family:        "ExtrusionLinePatt",
		Description:   "Description",
		FeatureValues: map[string]string{},
	},
	{
		Name:          "3_Extrusion",
		ProductType:   "LineExtrusion",
		Manufacturer:  "Erwepa",
		Family:        "ExtrusionLinePatt",
		Description:   "Description",
		FeatureValues: map[string]string{},
	},
	{
		Name:          "3_FB_Die",
		ProductType:   "FB_Die",
		Manufacturer:  "Coexpan",
		Family:        "ExtrusionLinePatt",
		Description:   "Description",
		FeatureValues: map[string]string{},
	},
	{
		Name:          "3_ExtruderDrive",
		ProductType:   "ExtruderDrive",
		Manufacturer:  "Coexpan",
		Family:        "ExtrusionLinePatt",
		Description:   "Description",
		FeatureValues: map[string]string{},
	},
	{
		Name:          "3_ExtruderHeating",
		ProductType:   "ExtruderHeating",
		Manufacturer:  "Coexpan",
		Family:        "ExtrusionLinePatt",
		Description:   "Description",
		FeatureValues: map[string]string{},
	},
	{
		Name:          "3_ExtruderPressure",
		ProductType:   "ExtruderPressure",
		Manufacturer:  "Coexpan",
		Family:        "ExtrusionLinePatt",
		Description:   "Description",
		FeatureValues: map[string]string{},
	},
	{
		Name:          "5_Stack",
		ProductType:   "LineStack",
		Manufacturer:  "Erwepa",
		Family:        "ExtrusionLinePatt",
		Description:   "Description",
		FeatureValues: map[string]string{},
	},
	{
		Name:          "5_Stack_Common",
		ProductType:   "LineStack_Common",
		Manufacturer:  "Erwepa",
		Family:        "ExtrusionLinePatt",
		Description:   "Description",
		FeatureValues: map[string]string{},
	},
	{
		Name:          "5_Stack_Cooling",
		ProductType:   "LineStack_Cooling",
		Manufacturer:  "Erwepa",
		Family:        "ExtrusionLinePatt",
		Description:   "Description",
		FeatureValues: map[string]string{},
	},
	{
		Name:          "5_Stack_Cyl",
		ProductType:   "LineStack_Cyl",
		Manufacturer:  "Kuhne",
		Family:        "ExtrusionLinePatt",
		Description:   "Description",
		FeatureValues: map[string]string{},
	},
	{
		Name:          "5_Stack_CylGAP",
		ProductType:   "LineStack_CylGAP",
		Manufacturer:  "Erwepa",
		Family:        "ExtrusionLinePatt",
		Description:   "Description",
		FeatureValues: map[string]string{},
	},

	{
		Name:          "8_Winders",
		ProductType:   "LineWinders",
		Manufacturer:  "Erwepa_Panday",
		Family:        "ExtrusionLinePatt",
		Description:   "Description",
		FeatureValues: map[string]string{},
	},
	{
		Name:          "8_Winders_Common",
		ProductType:   "LineWinders_Common",
		Manufacturer:  "Generic",
		Family:        "ExtrusionLinePatt",
		Description:   "Description",
		FeatureValues: map[string]string{},
	},
	{
		Name:          "8_Winders_WS",
		ProductType:   "LineWinders_WS",
		Manufacturer:  "Cattorini",
		Family:        "ExtrusionLinePatt",
		Description:   "Description",
		FeatureValues: map[string]string{},
	},
	{
		Name:          "8_Winders_W",
		ProductType:   "LineWinders_W",
		Manufacturer:  "Cattorini",
		Family:        "ExtrusionLinePatt",
		Description:   "Description",
		FeatureValues: map[string]string{},
	},

	{
		Name:          "HeatingZone",
		ProductType:   "HeatingZone",
		Manufacturer:  "Generic",
		Family:        "ExtrusionLinePatt",
		Description:   "Description",
		FeatureValues: map[string]string{},
	},
}
