package rP_General

import (
	"github.com/remrafvil/Auriga_API/internal/repositories/rProducts/rP_Types"
)

var FactoriesToCreate = []rP_Types.ProductCreationData{
	{
		Name:         "CX",
		ProductType:  "Factory",
		Manufacturer: "Coexpan",
		Family:       "Extrusion",
		Description:  "Factory Description",
		FeatureValues: map[string]string{
			"Site Code":   "28",
			"Latitude":    "40.47336694050559",
			"Longitude":   "-3.4062251035177815",
			"Country":     "Spain",
			"State":       "Madrid",
			"City":        "Alcalá de Henares",
			"Postal Code": "28802",
			"Address":     "Avda. Madrid Nº72",
		},
	},
	{
		Name:         "CXB",
		ProductType:  "Factory",
		Manufacturer: "Coexpan",
		Family:       "Extrusion",
		Description:  "Factory Description",
		FeatureValues: map[string]string{
			"Site Code":   "24",
			"Latitude":    "-21.95078036861139",
			"Longitude":   "-46.94069481274237",
			"Country":     "Brasil",
			"State":       "Sao Paulo",
			"City":        "Jundiai",
			"Postal Code": "143345",
			"Address":     "Luis Velezato, 500 (Condominio Jardin Hermida)'",
		},
	},
	{
		Name:         "CXC",
		ProductType:  "Factory",
		Manufacturer: "Coexpan",
		Family:       "Extrusion",
		Description:  "Factory Description",
		FeatureValues: map[string]string{
			"Site Code":   "25",
			"Latitude":    "-33.34656982991386",
			"Longitude":   "-70.71402877726321",
			"Country":     "Chile",
			"State":       "Santiago de Chile",
			"City":        "Quilicura",
			"Postal Code": "",
			"Address":     "Avda. Las Esteras Sur nº2591",
		},
	},
	{
		Name:         "CXD",
		ProductType:  "Factory",
		Manufacturer: "Coexpan",
		Family:       "Extrusion",
		Description:  "Factory Description",
		FeatureValues: map[string]string{
			"Site Code":   "27",
			"Latitude":    "49.8476805990264",
			"Longitude":   "7.881193995014542",
			"Country":     "Germany",
			"State":       "",
			"City":        "Bad Kreuznach",
			"Postal Code": "55543",
			"Address":     "Schwabenheimer Weg 105",
		},
	},
	{
		Name:         "CXE",
		ProductType:  "Factory",
		Manufacturer: "Coexpan",
		Family:       "Extrusion",
		Description:  "Factory Description",
		FeatureValues: map[string]string{
			"Site Code":   "28",
			"Latitude":    "40.47336694050559",
			"Longitude":   "-3.4062251035177815",
			"Country":     "Spain",
			"State":       "Madrid",
			"City":        "Alcalá de Henares",
			"Postal Code": "28802",
			"Address":     "Avda. Madrid Nº72",
		},
	},
	{
		Name:         "CXF",
		ProductType:  "Factory",
		Manufacturer: "Coexpan",
		Family:       "Extrusion",
		Description:  "Factory Description",
		FeatureValues: map[string]string{
			"Site Code":   "16",
			"Latitude":    "47.70713554646332",
			"Longitude":   "0.5913180833235019",
			"Country":     "France",
			"State":       "Angers",
			"City":        "Beaucouzé",
			"Postal Code": "B.P. 50065 - 49071",
			"Address":     "4 Avenue de la Fontaine",
		},
	},
	{
		Name:         "CXM",
		ProductType:  "Factory",
		Manufacturer: "Coexpan",
		Family:       "Extrusion",
		Description:  "Factory Description",
		FeatureValues: map[string]string{
			"Site Code":   "17",
			"Latitude":    "20.56960923286245",
			"Longitude":   "-100.28697891940746",
			"Country":     "Mexico",
			"State":       "Querétaro",
			"City":        "El Marques",
			"Postal Code": "76246",
			"Address":     "Avda. De las Fuentes N.º 78 Parque Industrial Finsa",
		},
	},
	{
		Name:         "EXT",
		ProductType:  "Factory",
		Manufacturer: "Coexpan",
		Family:       "Extrusion",
		Description:  "Factory Description",
		FeatureValues: map[string]string{
			"Site Code":   "18",
			"Latitude":    "0.0",
			"Longitude":   "0.0",
			"Country":     "Rusia",
			"State":       "Moscow",
			"City":        "Naro-Fominsk",
			"Postal Code": "S143300",
			"Address":     "MPO Kotovo, Individual street, building 18/3",
		},
	},
	{
		Name:         "FPC",
		ProductType:  "Factory",
		Manufacturer: "Coexpan",
		Family:       "Extrusion",
		Description:  "Factory Description",
		FeatureValues: map[string]string{
			"Site Code":   "19",
			"Latitude":    "47.04423838317513",
			"Longitude":   "6.160954244920862",
			"Country":     "France",
			"State":       "Chantrans",
			"City":        "",
			"Postal Code": "143345",
			"Address":     "",
		},
	},
	{
		Name:         "FPL",
		ProductType:  "Factory",
		Manufacturer: "Coexpan",
		Family:       "Extrusion",
		Description:  "Factory Description",
		FeatureValues: map[string]string{
			"Site Code":   "20",
			"Latitude":    "47.467032936785785",
			"Longitude":   "-0.6221996852106189",
			"Country":     "France",
			"State":       "Angers",
			"City":        "Beaucouzé",
			"Postal Code": "B.P. 50065 - 49071",
			"Address":     "4 Avenue de la Fontaine",
		},
	},
	{
		Name:         "FSP",
		ProductType:  "Factory",
		Manufacturer: "Coexpan",
		Family:       "Extrusion",
		Description:  "Factory Description",
		FeatureValues: map[string]string{
			"Site Code":   "21",
			"Latitude":    "49.70377268388635",
			"Longitude":   "2.7636446643239543",
			"Country":     "France",
			"State":       "Roye",
			"City":        "Roye",
			"Postal Code": "80700",
			"Address":     "Zone Industrielle Ouest",
		},
	},
	{
		Name:         "MNT",
		ProductType:  "Factory",
		Manufacturer: "Coexpan",
		Family:       "Extrusion",
		Description:  "Factory Description",
		FeatureValues: map[string]string{
			"Site Code":   "22",
			"Latitude":    "45.856921713900725",
			"Longitude":   "8.807748104410337",
			"Country":     "Italy",
			"State":       "Varese",
			"City":        "Sumirago",
			"Postal Code": "21040",
			"Address":     "Via Sandroni, 40",
		},
	},
	{
		Name:         "RTP",
		ProductType:  "Factory",
		Manufacturer: "Coexpan",
		Family:       "Extrusion",
		Description:  "Factory Description",
		FeatureValues: map[string]string{
			"Site Code":   "23",
			"Latitude":    "37.6931379454948",
			"Longitude":   "-6.617423984577194",
			"Country":     "Spain",
			"State":       "Huelva",
			"City":        "El Campillo",
			"Postal Code": "21650",
			"Address":     "Crta. A-461, KM. 51",
		},
	},
	{
		Name:         "ITC",
		ProductType:  "Factory",
		Manufacturer: "Coexpan",
		Family:       "Extrusion",
		Description:  "Factory Description",
		FeatureValues: map[string]string{
			"Site Code":   "30",
			"Latitude":    "40.47336694050559",
			"Longitude":   "-3.4062251035177815",
			"Country":     "Spain",
			"State":       "Madrid",
			"City":        "Alcalá de Henares",
			"Postal Code": "28802",
			"Address":     "Avda. Madrid Nº72",
		},
	},
}
