package rP_CXC_L8

import (
	"github.com/remrafvil/Auriga_API/internal/repositories/rProducts/rP_Types"
)

var CXC_L8_ProductsToCreate = []rP_Types.ProductCreationData{
	{
		Name:         "KS45-24D",
		ProductType:  "Extruder",
		Manufacturer: "Kuhne",
		Family:       "KS",
		Description:  "Extruder PP, PS",
		FeatureValues: map[string]string{
			"Type":       "Single Screw",
			"Diameter":   "45",
			"L/D Ratio":  "24",
			"Throughput": "90.0",
		},
	},
	{
		Name:         "K70EE-33D",
		ProductType:  "Extruder",
		Manufacturer: "Kuhne",
		Family:       "KHS",
		Description:  "Extruder PP, PS",
		FeatureValues: map[string]string{
			"Type":       "Single Screw",
			"Diameter":   "70",
			"L/D Ratio":  "33",
			"Throughput": "500.0",
		},
	},
	{
		Name:         "KS45-24D_B",
		ProductType:  "Extruder",
		Manufacturer: "Kuhne",
		Family:       "KS",
		Description:  "Extruder PP, PS",
		FeatureValues: map[string]string{
			"Type":       "Single Screw",
			"Diameter":   "45",
			"L/D Ratio":  "24",
			"Throughput": "90.0",
		},
	},

	{
		Name:         "KU5",
		ProductType:  "Feed-Block",
		Manufacturer: "Kuhne",
		Family:       "KU5",
		Description:  "Feed-Block PP, PS",
		FeatureValues: map[string]string{
			"Type":                    "KU5",
			"Weight":                  "45.0",
			"Dimensions":              "500x300x200",
			"Laminar Flow Geometry":   "Rectangular",
			"Laminar Flow Dimensions": "100x30",
			"Joins Pieces":            "0",
			"Extruders Connected":     "3",
			"Number of Layers":        "5",
			"Layer Configuration":     "A-B-A / A-B-C",
			"Layer Sequencer":         "Dynamic with adjustable distributor pins",
			"Layer Profiling Tool":    "Adjustable bolts",
			"Heating Zones":           "3",
			"Pressure Sensor":         "0",
		},
	},
	{
		Name:         "BDF117_601-17.A1.0.00.2.1",
		ProductType:  "Die",
		Manufacturer: "Kuhne",
		Family:       "BDF",
		Description:  "Die PP, PS",
		FeatureValues: map[string]string{
			"Type":                               "Coat Hanger",
			"Weight":                             "45.0",
			"Dimensions":                         "500x300x200",
			"Laminar Flow Geometry":              "Rectangular",
			"Laminar Flow Dimensions":            "100x30",
			"Lip Width":                          "1170",
			"Lip Thickness Range":                "0.5mm /1.5 mm",
			"Lip Static Interchangeable":         "Yes",
			"Deckling":                           "External Manual Adjustment",
			"Gap Adjustment":                     "With Flexible Lip",
			"Bolt Number":                        "34",
			"Bolt Diameter":                      "30",
			"Flow restrictor bar":                "Yes, located before the lip of the die",
			"Flow restrictor bar Adjustment":     "Manual by bolts",
			"Flow restrictor bar Bolts":          "17",
			"Flow restrictor bar Bolts Diameter": "70",
			"Heating Zones":                      "9",
		},
	},
	{
		Name:         "114264904SH-0026069-B-CD",
		ProductType:  "HeatingResistance",
		Manufacturer: "Kuhne",
		Family:       "HR",
		Description:  "Ceramic Heating Ressistance",
		FeatureValues: map[string]string{
			"Nominal Power":   "6",
			"Nominal Voltage": "400",
			"Nominal Current": "9.0",
			"Resistance":      "17.8",
			"Width":           "95",
			"Length":          "45",
			"Type":            "Ceramic",
		},
	},
	{
		Name:         "114264904SH-0026082-B-CD",
		ProductType:  "HeatingResistance",
		Manufacturer: "Kuhne",
		Family:       "HR",
		Description:  "Ceramic Heating Ressistance",
		FeatureValues: map[string]string{
			"Nominal Power":   "6",
			"Nominal Voltage": "400",
			"Nominal Current": "9.0",
			"Resistance":      "17.8",
			"Width":           "95",
			"Length":          "45",
			"Type":            "Ceramic",
		},
	},
	{
		Name:         "114264904_EA02-0400_02042",
		ProductType:  "Blower",
		Manufacturer: "Kuhne",
		Family:       "Extruder_Blower",
		Description:  "DNG3-6/WS",
		FeatureValues: map[string]string{
			"Nominal Power":   "0.09",
			"Nominal Voltage": "400",
			"Nominal Current": "0.26",
			"Nominal Speed":   "2785",
			"Frequency":       "50",
			"Air Flow":        "223",
		},
	},
	{
		Name:         "Thermocouple_J",
		ProductType:  "TemperatureSensor",
		Manufacturer: "Coexpan",
		Family:       "Sensors",
		Description:  "Thermocouple_J",
		FeatureValues: map[string]string{
			"Type":            "Thermocouple J",
			"Measuring Range": "0-750",
		},
	},
	{
		Name:         "RSG_116443-002",
		ProductType:  "Gearbox",
		Manufacturer: "RS_Getriebe",
		Family:       "FEX250",
		Description:  "Extruder Gearbox",
		FeatureValues: map[string]string{
			"Type":           "Parallel Shaft",
			"Ratio":          "9.88",
			"Nominal Torque": "1066",
			"Maximum Torque": "1843",
			"Motor Power":    "33.5",
			"Motor Speed":    "3125",
			"Output Speed":   "316",
			"Weight":         "195",
			"Oil Type":       "CLP 220",
			"Oil Volume":     "7.5",
		},
	},
	{
		Name:         "RSG_73003262-003",
		ProductType:  "Gearbox",
		Manufacturer: "RS_Getriebe",
		Family:       "FEX250",
		Description:  "Extruder Gearbox",
		FeatureValues: map[string]string{
			"Type":           "Parallel Shaft",
			"Ratio":          "9.88",
			"Nominal Torque": "1843",
			"Maximum Torque": "1843",
			"Motor Power":    "30",
			"Motor Speed":    "1555",
			"Output Speed":   "157",
			"Weight":         "",
			"Oil Type":       "CLP 220",
			"Oil Volume":     "7.5",
		},
	},
	{
		Name:         "CMG 61 1-4_G",
		ProductType:  "Gearbox",
		Manufacturer: "Knödler",
		Family:       "CMG",
		Description:  "Extruder Gearbox",
		FeatureValues: map[string]string{
			"Type":           "Planetary",
			"Ratio":          "5.89",
			"Nominal Torque": "3200",
			"Maximum Torque": "3341",
			"Motor Power":    "147",
			"Motor Speed":    "2406",
			"Output Speed":   "600",
			"Weight":         "",
			"Oil Type":       "VG 220",
			"Oil Volume":     "15",
		},
	},
	{
		Name:         "MDFMAXX 180-12",
		ProductType:  "Motor_AC",
		Manufacturer: "Lenze",
		Family:       "1PH8",
		Description:  "Motor HDP",
		FeatureValues: map[string]string{
			"Nominal Power":    "32.5",
			"Stator Voltage":   "400.0",
			"Stator Current":   "58.80",
			"Nominal Speed":    "2585.0",
			"Frequency":        "87.0",
			"Power Factor":     "",
			"Efficiency":       "",
			"Torque":           "",
			"Maximum Speed":    "",
			"Water Flow":       "0",
			"Weight":           "",
			"Frame":            "",
			"Cooling":          "AirCooling: Forze",
			"TempSensor":       "PTC",
			"MountingPosition": "IMB5",
			"InsulationClass":  "H",
			"EfficiencyClass":  "",
			"Bearing_DE":       "",
			"Bearing_NDE":      "",
		},
	},
	{
		Name:         "1PH8137-1AF22-2BB2-Z",
		ProductType:  "Motor_AC",
		Manufacturer: "Siemens",
		Family:       "1PH8",
		Description:  "Motor HDP",
		FeatureValues: map[string]string{
			"Nominal Power":    "31.5",
			"Stator Voltage":   "364.0",
			"Stator Current":   "67.0",
			"Nominal Speed":    "1750.0",
			"Frequency":        "59.9",
			"Power Factor":     "0.86",
			"Efficiency":       "87.9",
			"Torque":           "25.5",
			"Maximum Speed":    "3000.0",
			"Water Flow":       "0",
			"Weight":           "157.0",
			"Frame":            "",
			"Cooling":          "WaterCooling",
			"TempSensor":       "PTC",
			"MountingPosition": "IMB5",
			"InsulationClass":  "H",
			"EfficiencyClass":  "",
			"Bearing_DE":       "",
			"Bearing_NDE":      "",
		},
	},
	{
		Name:         "CMG 61 1-4_M",
		ProductType:  "Motor_AC",
		Manufacturer: "Knödler",
		Family:       "CMG",
		Description:  "Motor HDP",
		FeatureValues: map[string]string{
			"Nominal Power":    "147.0",
			"Stator Voltage":   "375.0",
			"Stator Current":   "309.0",
			"Nominal Speed":    "2406.0",
			"Frequency":        "82.0",
			"Power Factor":     "0.84",
			"Efficiency":       "",
			"Torque":           "",
			"Maximum Speed":    "",
			"Water Flow":       "0",
			"Weight":           "",
			"Frame":            "",
			"Cooling":          "AirCooling: Forze",
			"TempSensor":       "KTY",
			"MountingPosition": "IMB5",
			"InsulationClass":  "F",
			"EfficiencyClass":  "",
			"Bearing_DE":       "",
			"Bearing_NDE":      "",
		},
	},
	{
		Name:         "01536EP3E254T",
		ProductType:  "Motor_AC",
		Manufacturer: "Weg",
		Family:       "W21",
		Description:  "Motor W21",
		FeatureValues: map[string]string{
			"Nominal Power":    "11.0",
			"Stator Voltage":   "380.0",
			"Stator Current":   "21.50",
			"Nominal Speed":    "2950.0",
			"Frequency":        "50.0",
			"Power Factor":     "0.90",
			"Efficiency":       "90.2",
			"Torque":           "",
			"Maximum Speed":    "",
			"Water Flow":       "0",
			"Weight":           "116.12",
			"Frame":            "254T",
			"Cooling":          "AirCooling",
			"TempSensor":       "",
			"MountingPosition": "IMB3",
			"InsulationClass":  "E",
			"EfficiencyClass":  "",
			"Bearing_DE":       "",
			"Bearing_NDE":      "",
		},
	},
	{
		Name:         "AF132M/2D-11L_50059330147",
		ProductType:  "Motor_AC",
		Manufacturer: "ATB",
		Family:       "W21",
		Description:  "Motor ATB",
		FeatureValues: map[string]string{
			"Nominal Power":    "11.0",
			"Stator Voltage":   "400.0",
			"Stator Current":   "22.00",
			"Nominal Speed":    "2920.0",
			"Frequency":        "50.0",
			"Power Factor":     "0.88",
			"Efficiency":       "",
			"Torque":           "",
			"Maximum Speed":    "",
			"Water Flow":       "0",
			"Weight":           "67.0",
			"Frame":            "132M",
			"Cooling":          "AirCooling",
			"TempSensor":       "",
			"MountingPosition": "IMB5",
			"InsulationClass":  "F",
			"EfficiencyClass":  "",
			"Bearing_DE":       "",
			"Bearing_NDE":      "",
		},
	},
	{
		Name:         "MAC14L35-RS0B0-B24R-STBF10N-R0SU",
		ProductType:  "Motor_AC",
		Manufacturer: "Lenze",
		Family:       "MAC",
		Description:  "Motor MAC",
		FeatureValues: map[string]string{
			"Nominal Power":    "3.9",
			"Stator Voltage":   "390.0",
			"Stator Current":   "9.10",
			"Nominal Speed":    "3455.0",
			"Frequency":        "120.0",
			"Power Factor":     "0.80",
			"Efficiency":       "",
			"Torque":           "13.5",
			"Maximum Speed":    "",
			"Water Flow":       "0",
			"Weight":           "",
			"Frame":            "",
			"Cooling":          "AirCooling: Forze",
			"TempSensor":       "KTY",
			"MountingPosition": "IMB5",
			"InsulationClass":  "F",
			"EfficiencyClass":  "",
			"Bearing_DE":       "",
			"Bearing_NDE":      "",
		},
	},
	{
		Name:         "4656EZ",
		ProductType:  "Motor_AC",
		Manufacturer: "Lenze",
		Family:       "EZ",
		Description:  "Motor Fan",
		FeatureValues: map[string]string{
			"Nominal Power":    "0.019",
			"Stator Voltage":   "230.0",
			"Stator Current":   "0.12",
			"Nominal Speed":    "2600.0",
			"Frequency":        "50.0",
			"Power Factor":     "",
			"Efficiency":       "",
			"Torque":           "",
			"Maximum Speed":    "",
			"Water Flow":       "0",
			"Weight":           "",
			"Frame":            "",
			"Cooling":          "",
			"TempSensor":       "",
			"MountingPosition": "",
			"InsulationClass":  "B",
			"EfficiencyClass":  "",
			"Bearing_DE":       "",
			"Bearing_NDE":      "",
		},
	},
	{
		Name:         "MAC14L20-RS0B0-N24R-STBS00N-R0SU",
		ProductType:  "Motor_AC",
		Manufacturer: "Lenze",
		Family:       "MAC",
		Description:  "Motor MAC",
		FeatureValues: map[string]string{
			"Nominal Power":    "1.4",
			"Stator Voltage":   "390.0",
			"Stator Current":   "3.30",
			"Nominal Speed":    "2000.0",
			"Frequency":        "70.0",
			"Power Factor":     "0.75",
			"Efficiency":       "",
			"Torque":           "6.7",
			"Maximum Speed":    "",
			"Water Flow":       "0",
			"Weight":           "",
			"Frame":            "",
			"Cooling":          "AirCooling: Forze",
			"TempSensor":       "KTY",
			"MountingPosition": "IMB5",
			"InsulationClass":  "F",
			"EfficiencyClass":  "",
			"Bearing_DE":       "",
			"Bearing_NDE":      "",
		},
	},
	{
		Name:         "IE0-A-7-M-B05C-1-4-0-P-E-D141430B000X0",
		ProductType:  "PressureSensor",
		Manufacturer: "Gefran",
		Family:       "IE",
		Description:  "Without Transmission Fluid",
		FeatureValues: map[string]string{
			"Type":            "Pressure-Safety",
			"Measuring Range": "500",
			"Nominal Voltage": "10-30",
			"Signal Type":     "4-20mA",
			"Calibration":     "80%",
		},
	},

	{
		Name:         "IE0-A-7-M-B05C-1-4-0-P-E-D142130B000X0",
		ProductType:  "PressureSensor",
		Manufacturer: "Gefran",
		Family:       "IE",
		Description:  "Without Transmission Fluid",
		FeatureValues: map[string]string{
			"Type":            "Pressure-Safety",
			"Measuring Range": "500",
			"Nominal Voltage": "10-30",
			"Signal Type":     "4-20mA",
			"Calibration":     "80%",
		},
	},
	{
		Name:         "ME0-6-M-B05C-1-4-0-E-2130X000X00",
		ProductType:  "PressureSensor",
		Manufacturer: "Gefran",
		Family:       "ME",
		Description:  "Without Transmission Fluid",
		FeatureValues: map[string]string{
			"Type":            "Pressure-Safety",
			"Measuring Range": "500",
			"Nominal Voltage": "13-30",
			"Signal Type":     "4-20mA",
			"Calibration":     "80%",
		},
	},
	{
		Name:         "MDT460F-1/2-5C-15",
		ProductType:  "PressureSensor",
		Manufacturer: "Dynisco",
		Family:       "MDT4X2F",
		Description:  "Extruder Pressure Sensor",
		FeatureValues: map[string]string{
			"Type":            "Pressure-Safety",
			"Measuring Range": "500",
			"Nominal Voltage": "24",
			"Signal Type":     "4-20mA",
			"Calibration":     "80%",
		},
	},
	{
		Name:         "RPM0150MD701S1G1100",
		ProductType:  "PositionSensorsMagnetostrictive",
		Manufacturer: "Temposinic",
		Family:       "R-series",
		Description:  "Extruder Pressure Sensor",
		FeatureValues: map[string]string{
			"Type":            "Magnetostrictive",
			"Bit":             "25 Gray",
			"Measuring Range": "150",
			"Accuracy":        "0.005",
			"Gradient":        "2816.67",
			"Protocol":        "SSI",
		},
	},

	{
		Name:         "T005616",
		ProductType:  "ScreenChanger",
		Manufacturer: "BD-Plast",
		Family:       "BDL",
		Description:  "BDL 48/45",
		FeatureValues: map[string]string{
			"Type":             "Manual",
			"Dimension":        "45",
			"Number of Plates": "1",
		},
	},
	{
		Name:         "CSC-116",
		ProductType:  "ScreenChanger",
		Manufacturer: "Maag",
		Family:       "CSC",
		Description:  "1104878",
		FeatureValues: map[string]string{
			"Type":             "Manual",
			"Dimension":        "106",
			"Number of Plates": "2",
			"Max. Flow":        "600",
		},
	},
	{
		Name:         "EX56-5_GP",
		ProductType:  "MeltPump",
		Manufacturer: "Maag",
		Family:       "Extrex",
		Description:  "BDL 48/45",
		FeatureValues: map[string]string{
			"Dimension":          "56",
			"Volume":             "92.6",
			"Max. Pressure Drop": "170",
			"Max. Flow":          "540",
		},
	},
	{
		Name:         "MI0120B2X4_CNX6",
		ProductType:  "DegassingSystem",
		Manufacturer: "Busch",
		Family:       "Plastex",
		Description:  "Vacuum System",
		FeatureValues: map[string]string{
			"Type":        "Vacuum System",
			"Max. Flow":   "120",
			"Max. Vacuum": "20",
		},
	},
	{
		Name:         "MI2122BV01",
		ProductType:  "VacuumPump",
		Manufacturer: "Busch",
		Family:       "MINK",
		Description:  "Claw Vacuum Pump",
		FeatureValues: map[string]string{
			"Type":        "Claw",
			"Max. Flow":   "120",
			"Max. Vacuum": "20",
		},
	},
	{
		Name:         "CXC_L8_TG2_VP_Elmo",
		ProductType:  "VacuumPump",
		Manufacturer: "Elmo Rietschle",
		Family:       "G-BH1",
		Description:  "Lateral Channel",
		FeatureValues: map[string]string{
			"Type":        "Lateral Channel",
			"Max. Flow":   "",
			"Max. Vacuum": "",
		},
	},
	{
		Name:         "CXC_L8_TG1_VP_XX",
		ProductType:  "VacuumPump",
		Manufacturer: "XX",
		Family:       "XX",
		Description:  "Rotative Lobe",
		FeatureValues: map[string]string{
			"Type":        "Lobe",
			"Max. Flow":   "",
			"Max. Vacuum": "",
		},
	},
	{
		Name:         "AMHE100LBA2",
		ProductType:  "Motor_AC",
		Manufacturer: "Lafert",
		Family:       "AMHEG",
		Description:  "Motor AC",
		FeatureValues: map[string]string{
			"Nominal Power":    "4.2",
			"Stator Voltage":   "400.0",
			"Stator Current":   "8.40",
			"Nominal Speed":    "2905.0",
			"Frequency":        "50.0",
			"Power Factor":     "0.84",
			"Efficiency":       "87.1",
			"Torque":           "",
			"Maximum Speed":    "",
			"Water Flow":       "0",
			"Weight":           "26.2",
			"Frame":            "",
			"Cooling":          "AirCooling",
			"TempSensor":       "",
			"MountingPosition": "IMB5",
			"InsulationClass":  "F",
			"EfficiencyClass":  "IE2",
			"Bearing_DE":       "",
			"Bearing_NDE":      "",
		},
	},
	{
		Name:         "GKS07-3MVBR112C32",
		ProductType:  "Gearbox",
		Manufacturer: "Lenze",
		Family:       "GKS",
		Description:  "Extruder Gearbox",
		FeatureValues: map[string]string{
			"Type":           "Parallel Shaft",
			"Ratio":          "23.11",
			"Nominal Torque": "796",
			"Maximum Torque": "796",
			"Motor Power":    "9.7",
			"Motor Speed":    "2555",
			"Output Speed":   "110.6",
			"Weight":         "",
			"Oil Type":       "CLP 460",
			"Oil Volume":     "",
		},
	},
	{
		Name:         "MDFMARS-112C32C0C",
		ProductType:  "Motor_AC",
		Manufacturer: "Lenze",
		Family:       "MDF",
		Description:  "Motor AC",
		FeatureValues: map[string]string{
			"Nominal Power":    "9.7",
			"Stator Voltage":   "400.0",
			"Stator Current":   "21.7",
			"Nominal Speed":    "2555.0",
			"Frequency":        "87.0",
			"Power Factor":     "0.75",
			"Efficiency":       "",
			"Torque":           "",
			"Maximum Speed":    "",
			"Water Flow":       "0",
			"Weight":           "26.2",
			"Frame":            "",
			"Cooling":          "AirCooling: Forze",
			"TempSensor":       "KTY",
			"MountingPosition": "",
			"InsulationClass":  "F",
			"EfficiencyClass":  "IE1",
			"Bearing_DE":       "",
			"Bearing_NDE":      "",
		},
	},
	{
		Name:         "GKR05-2A_SAR_14LN20 _345_C303",
		ProductType:  "Gearbox",
		Manufacturer: "Lenze",
		Family:       "GKR",
		Description:  "Calander Gearbox",
		FeatureValues: map[string]string{
			"Type":           "Parallel Shaft",
			"Ratio":          "33.433",
			"Nominal Torque": "213",
			"Maximum Torque": "213",
			"Motor Power":    "",
			"Motor Speed":    "",
			"Output Speed":   "59.8",
			"Weight":         "",
			"Oil Type":       "CLP HC 320",
			"Oil Volume":     "",
		},
	},
	{
		Name:         "GKS09-2N_SAR_4E_1344A300",
		ProductType:  "Gearbox",
		Manufacturer: "Lenze",
		Family:       "GKS",
		Description:  "Calander Gearbox",
		FeatureValues: map[string]string{
			"Type":           "Parallel Shaft",
			"Ratio":          "125.641",
			"Nominal Torque": "3080",
			"Maximum Torque": "3080",
			"Motor Power":    "",
			"Motor Speed":    "",
			"Output Speed":   "22.3",
			"Weight":         "",
			"Oil Type":       "CLP 460",
			"Oil Volume":     "",
		},
	},
	{
		Name:         "S-TT-95/18-40-22-LC",
		ProductType:  "WaterCoolingUnit",
		Manufacturer: "Frigotrol",
		Family:       "S-TT",
		Description:  "Cooling Unit",
		FeatureValues: map[string]string{
			"Type":             "Direct Cooling",
			"Max. Pressure":    "6",
			"Max. Temperature": "95",
			"Min. Temperature": "15",
			"Nominal Power":    "22.5",
			"Nominal Current":  "38.5",
			"Nominal Voltage":  "400",
			"Control Voltage":  "24",
		},
	},

	{
		Name:         "1LE0323-0EB442-2FB4-Z",
		ProductType:  "Motor_AC",
		Manufacturer: "Siemens",
		Family:       "1LE",
		Description:  "Motor AC",
		FeatureValues: map[string]string{
			"Nominal Power":    "1.5",
			"Stator Voltage":   "400.0",
			"Stator Current":   "3.2",
			"Nominal Speed":    "1440.0",
			"Frequency":        "50.0",
			"Power Factor":     "0.79",
			"Efficiency":       "85.3",
			"Torque":           "",
			"Maximum Speed":    "",
			"Water Flow":       "0",
			"Weight":           "22.0",
			"Frame":            "90L",
			"Cooling":          "AirCooling: Forze",
			"TempSensor":       "",
			"MountingPosition": "IMB5",
			"InsulationClass":  "F",
			"EfficiencyClass":  "IE3",
			"Bearing_DE":       "6205-2Z_C3",
			"Bearing_NDE":      "6205-2Z_C3",
		},
	},

	{
		Name:         "1LE0323-1AB52-2FB4-Z",
		ProductType:  "Motor_AC",
		Manufacturer: "Siemens",
		Family:       "1LE",
		Description:  "Motor AC",
		FeatureValues: map[string]string{
			"Nominal Power":    "3.0",
			"Stator Voltage":   "400.0",
			"Stator Current":   "6.1",
			"Nominal Speed":    "1450.0",
			"Frequency":        "50.0",
			"Power Factor":     "0.81",
			"Efficiency":       "87.7",
			"Torque":           "",
			"Maximum Speed":    "",
			"Water Flow":       "0",
			"Weight":           "36.0",
			"Frame":            "100L",
			"Cooling":          "AirCooling: Forze",
			"TempSensor":       "",
			"MountingPosition": "IMB5",
			"InsulationClass":  "F",
			"EfficiencyClass":  "IE3",
			"Bearing_DE":       "6206-2Z_C3",
			"Bearing_NDE":      "6206-2Z_C3",
		},
	},

	{
		Name:         "1LE0323-1BB52-2FB4-Z",
		ProductType:  "Motor_AC",
		Manufacturer: "Siemens",
		Family:       "1LE",
		Description:  "Motor AC",
		FeatureValues: map[string]string{
			"Nominal Power":    "4.0",
			"Stator Voltage":   "400.0",
			"Stator Current":   "8.1",
			"Nominal Speed":    "1450.0",
			"Frequency":        "50.0",
			"Power Factor":     "0.81",
			"Efficiency":       "88.6",
			"Torque":           "",
			"Maximum Speed":    "",
			"Water Flow":       "0",
			"Weight":           "36.0",
			"Frame":            "112M",
			"Cooling":          "AirCooling: Forze",
			"TempSensor":       "",
			"MountingPosition": "IMB5",
			"InsulationClass":  "F",
			"EfficiencyClass":  "IE3",
			"Bearing_DE":       "6206-2Z_C3",
			"Bearing_NDE":      "6206-2Z_C3",
		},
	},

	{
		Name:         "B32_IL-2-2",
		ProductType:  "Motor_AC",
		Manufacturer: "Sovem",
		Family:       "B32",
		Description:  "Motor Fan AC",
		FeatureValues: map[string]string{
			"Nominal Power":    "0.059",
			"Stator Voltage":   "220.0",
			"Stator Current":   "0.29",
			"Nominal Speed":    "",
			"Frequency":        "50.0",
			"Power Factor":     "",
			"Efficiency":       "",
			"Torque":           "",
			"Maximum Speed":    "",
			"Water Flow":       "0",
			"Weight":           "",
			"Frame":            "",
			"Cooling":          "AirCooling",
			"TempSensor":       "",
			"MountingPosition": "",
			"InsulationClass":  "F",
			"EfficiencyClass":  "",
			"Bearing_DE":       "",
			"Bearing_NDE":      "",
		},
	},
	{
		Name:         "TN71C/4_14-2-2",
		ProductType:  "Motor_AC",
		Manufacturer: "MT Motori Elettrici",
		Family:       "TN",
		Description:  "Motor AC",
		FeatureValues: map[string]string{
			"Nominal Power":    "0.55",
			"Stator Voltage":   "400.0",
			"Stator Current":   "1.65",
			"Nominal Speed":    "1390",
			"Frequency":        "50.0",
			"Power Factor":     "0.67",
			"Efficiency":       "77.1",
			"Torque":           "",
			"Maximum Speed":    "",
			"Water Flow":       "0",
			"Weight":           "",
			"Frame":            "",
			"Cooling":          "AirCooling",
			"TempSensor":       "",
			"MountingPosition": "",
			"InsulationClass":  "F",
			"EfficiencyClass":  "IE2",
			"Bearing_DE":       "",
			"Bearing_NDE":      "",
		},
	},
	{
		Name:         "KC90-2225220007_22A301",
		ProductType:  "Gearbox",
		Manufacturer: "Tramec",
		Family:       "K",
		Description:  "Winders Gearbox",
		FeatureValues: map[string]string{
			"Type":              "Spiroplan",
			"Ratio":             "10.0",
			"Nominal Torque":    "236",
			"Maximum Torque":    "236",
			"Motor Power":       "4",
			"Motor Speed":       "1400",
			"Output Speed":      "",
			"Weight":            "16.4",
			"Oil Type":          "WE 320",
			"Oil Volume":        "0.8",
			"Service Factor":    "1.3",
			"Mounting Position": "B8",
		},
	},
	{
		Name:         "KC90-2225220009_22A301",
		ProductType:  "Gearbox",
		Manufacturer: "Tramec",
		Family:       "K",
		Description:  "Winders Gearbox",
		FeatureValues: map[string]string{
			"Type":              "Spiroplan",
			"Ratio":             "15.0",
			"Nominal Torque":    "256",
			"Maximum Torque":    "235",
			"Motor Power":       "3",
			"Motor Speed":       "1400",
			"Output Speed":      "",
			"Weight":            "16.4",
			"Oil Type":          "WE 320",
			"Oil Volume":        "0.8",
			"Service Factor":    "1.3",
			"Mounting Position": "B8",
		},
	},
	{
		Name:         "TC90B-2012439005_01V006",
		ProductType:  "Gearbox",
		Manufacturer: "Tramec",
		Family:       "T",
		Description:  "Winders Gearbox",
		FeatureValues: map[string]string{
			"Type":              "Helical Bevel",
			"Ratio":             "12.5",
			"Nominal Torque":    "338",
			"Maximum Torque":    "338",
			"Motor Power":       "4",
			"Motor Speed":       "1400",
			"Output Speed":      "",
			"Weight":            "25.0",
			"Oil Type":          "WE 320",
			"Oil Volume":        "",
			"Service Factor":    "1.6",
			"Mounting Position": "B3",
		},
	},
	{
		Name:         "RCV352P_071222",
		ProductType:  "Gearbox",
		Manufacturer: "Varmec",
		Family:       "RCV",
		Description:  "Winders Gearbox",
		FeatureValues: map[string]string{
			"Type":              "In Line Helical",
			"Ratio":             "19.21",
			"Nominal Torque":    "377",
			"Maximum Torque":    "377",
			"Motor Power":       "3",
			"Motor Speed":       "1400",
			"Output Speed":      "",
			"Weight":            "4.0",
			"Oil Type":          "WG 320",
			"Oil Volume":        "1.3",
			"Service Factor":    "1.1",
			"Mounting Position": "B3",
		},
	},
	{
		Name:         "XF50-2162724002_16A501",
		ProductType:  "Gearbox",
		Manufacturer: "Tramec",
		Family:       "X",
		Description:  "Winders Gearbox",
		FeatureValues: map[string]string{
			"Type":              "Helical Bevel",
			"Ratio":             "15.0",
			"Nominal Torque":    "74",
			"Maximum Torque":    "74",
			"Motor Power":       "0.9",
			"Motor Speed":       "1400",
			"Output Speed":      "",
			"Weight":            "4.0",
			"Oil Type":          "WE 320",
			"Oil Volume":        "0.08",
			"Service Factor":    "1.0",
			"Mounting Position": "V6",
		},
	},
}
